FROM --platform=linux/amd64 python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY models/all-MiniLM-L6-v2 /app/models/all-MiniLM-L6-v2

COPY src/round1b/ .

CMD ["python", "main.py"]
